services:
  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    ports:
      - "50123:8080"

  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    ports:
      - "50124:8080"

  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile
    ports:
      - "50125:8080"